import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { ThemeProvider } from "../component/theme-provider";
=======
>>>>>>> origin/Cordigram-social-chat

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cordigram",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
<<<<<<< HEAD
      <body className={`${roboto.variable} antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
=======
      <body className={`${roboto.variable} antialiased`}>{children}</body>
>>>>>>> origin/Cordigram-social-chat
    </html>
  );
}
