import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../component/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";
import { LanguageProvider } from "../component/language-provider";

export const metadata: Metadata = {
  title: "Cordigram",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
};

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const storedLocale = cookieStore.get("NEXT_LOCALE")?.value;
  const locale =
    storedLocale === "vi" || storedLocale === "en" ? storedLocale : "en";
  const messages = (await import(`../messages/${locale}.json`)).default;
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="antialiased">
        <NextIntlClientProvider messages={messages} locale={locale}>
          <LanguageProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </LanguageProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
