<<<<<<< HEAD
"use client";

import Sidebar from "@/ui/Sidebar/sidebar";
import { usePathname } from "next/navigation";
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import Sidebar from "@/ui/Sidebar/sidebar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cordigram",
  description: "Generated by create next app",
};
>>>>>>> origin/Cordigram-social-chat

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
  const pathname = usePathname();
  const isMessagesPage = pathname?.startsWith("/messages");

  if (isMessagesPage) {
    return <>{children}</>;
  }

  return (
    <div className="app-shell">
      <Sidebar />
      <div className="page">{children}</div>
=======
  return (
    <div className="app-shell flex">
      <Sidebar />
      <div className="page flex-1">{children}</div>
>>>>>>> origin/Cordigram-social-chat
    </div>
  );
}
