import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import Sidebar from "@/ui/Sidebar/sidebar";
import { AuthGuard } from "../../component/auth-guard";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cordigram",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthGuard>
      <div className="app-shell flex">
        <Sidebar />
        <div className="page flex-1" data-scroll-root>
          {children}
        </div>
      </div>
    </AuthGuard>
  );
}
